export const CharacterClasses = [
  {
    name: "Cleric",
    requirements: [0, 0, 0, 0, 0, 0],
    hitDie: 6,
    armor: "Any, including shields",
    Weapons: "Any blunt weapons",
    Languages: "Alignment, Common",
    baseTHAC0: 19,
    savingThrows: [11, 12, 14, 16, 15],
    spells: [0, 0, 0, 0, 0],
  },
  {
    name: "Dwarf",
    requirements: [0, 0, 9, 0, 0, 0],
    hitDie: 8,
    armor: "Any, including shields",
    Weapons: "Small or normal sized",
    Languages: "Alignment, Common, Dwarvish, Gnomish, Goblin, Kobold",
    baseTHAC0: 19,
    savingThrows: [8, 9, 10, 13, 12],
    spells: false,
  },
  {
    name: "Elf",
    requirements: [0, 0, 0, 9, 0, 0],
    hitDie: 6,
    armor: "Any, including shields",
    Weapons: "Any",
    Languages: "Alignment, Common, Elvish, Gnoll, Hobgoblin, Orcish",
    baseTHAC0: 19,
    savingThrows: [12, 13, 13, 15, 15],
    spells: [1, 0, 0, 0, 0],
  },
  {
    name: "Fighter",
    requirements: [0, 0, 0, 0, 0, 0],
    hitDie: 8,
    armor: "Any, including shields",
    Weapons: "Any",
    Languages: "Alignment, Common",
    baseTHAC0: 19,
    savingThrows: [12, 13, 14, 15, 16],
    spells: false,
  },
  {
    name: "Halfling",
    requirements: [0, 9, 9, 0, 0, 0],
    hitDie: 6,
    armor: "Any, appropraite to size, including shields",
    Weapons: "Any appropriate to size",
    Languages: "Alignment, Common, Halfling",
    baseTHAC0: 19,
    savingThrows: [8, 9, 10, 13, 12],
    spells: false,
  },
  {
    name: "Magic-User",
    requirements: false,
    hitDie: 4,
    armor: "None",
    Weapons: "Dagger",
    Languages: "Alignment, Common",
    baseTHAC0: 19,
    savingThrows: [13, 14, 13, 16, 15],
    spells: [1, 0, 0, 0, 0, 0],
  },
  {
    name: "Thief",
    requirements: [0, 0, 0, 0, 0, 0],
    hitDie: 4,
    armor: "Leather, no shields",
    Weapons: "Any",
    Languages: "Alignment, Common",
    baseTHAC0: 19,
    savingThrows: [13, 14, 13, 16, 15],
    spells: false,
  },
];
